### PR TITLE
Faster Inference by TensorRT

### PR DESCRIPTION
**Pull request by SnowMasaya**
Web camera input apply TensorRT

Jetson Xavier JetPack 4.2 case
- Normal case: Average 17FPS
- TensorRT case: Average 23FPS

https://developer.nvidia.com/tensorrt

### CODE REVIEW

**Comment by tilink** [comment]
Hi @SnowMasaya - do you think this could work for the TX2 as well? I tried and am getting errors, this one to start (I tried getting around it but no luck):

`$ python3 run_webcam.py --model=mobilenet_thin --resize=432x368 --camera=1 --tensorrt=True
Traceback (most recent call last):
  File "run_webcam.py", line 45, in <module>
    e = TfPoseEstimator(get_graph_path(args.model), target_size=(w, h), trt_bool=str2bool(args.tensorrt))
  File "/media/nvidia/c2e480bf-240c-4484-bc9c-0d36da3d46ba/tf-pose-estimation/tf_pose/estimator.py", line 327, in __init__
    use_calibration=True,
TypeError: create_inference_graph() got an unexpected keyword argument 'is_dynamic_op'`

Can you tell me what version of Tensorflow you're running, and anything else you think would be applicable to figuring out what's different? Thank you!

**Comment by bdatdo0601** [comment]
@tilink I managed to run on TX2 without any problem by downloading one of the TX2's Tensorflow `whl` file from [here](https://developer.download.nvidia.com/compute/redist/jp/v42). 

@SnowMasaya Is it possible to export optimized tensorRT graph out to file system? That way we don't have to calculate the new graph every time

**Comment by SnowMasaya** [comment]
@tilink TensorFlow version is "1.13.1+nv19.4"

@bdatdo0601 Following example code export a TensorRT graph

```
            graph_def = trt.create_inference_graph(
                graph_def,
                output_nodes,
                max_batch_size=1,
                max_workspace_size_bytes=1 << 20,
                precision_mode="FP16",
                # precision_mode="INT8",
                minimum_segment_size=3,
                is_dynamic_op=True,
                maximum_cached_engines=int(1e3),
                use_calibration=True,
            )
            with open('open_pose_trt.pb', 'wb') as f:
                f.write(graph_def .SerializeToString())
```

**Comment by ildoonet** [comment]
Thanks!!

**Comment by willfu** [comment]
@SnowMasaya I used tx2 jetpack 4.2.1 + tensorflow_gpu-1.14.0+nv19.7-cp36-cp36m-linux_aarch64.whl, the default fps is just 5fps, which is far behind the one you mentioned 17 fps. Is there any special configuration? thanks.

Another thing is when I used tensorrt, it failed with below msg, is it because compatiblity with tensorflow 1.14.0? thanks.

will@will-desktop:~/tf-pose-estimation$ python3 run_webcam.py --model=mobilenet_thin --resize=432x368 --camera=1 --tensorrt=True
2019-08-11 18:03:18.585491: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
np_resource = np.dtype([("resource", np.ubyte, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
np_resource = np.dtype([("resource", np.ubyte, 1)])
2019-08-11 18:03:30.661049: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
WARNING: Logging before flag parsing goes to stderr.
W0811 18:03:30.744550 547506102288 deprecation_wrapper.py:119] From /home/will/tf-pose-estimation/tf_pose/mobilenet/mobilenet.py:369: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.

[2019-08-11 18:03:35,496] [TfPoseEstimator-WebCam] [DEBUG] initialization mobilenet_thin : /home/will/tf-pose-estimation/models/graph/mobilenet_thin/graph_opt.pb
I0811 18:03:35.496699 547506102288 run_webcam.py:42] initialization mobilenet_thin : /home/will/tf-pose-estimation/models/graph/mobilenet_thin/graph_opt.pb
[2019-08-11 18:03:35,498] [TfPoseEstimator] [INFO] loading graph from /home/will/tf-pose-estimation/models/graph/mobilenet_thin/graph_opt.pb(default size=432x368)
I0811 18:03:35.498320 547506102288 estimator.py:310] loading graph from /home/will/tf-pose-estimation/models/graph/mobilenet_thin/graph_opt.pb(default size=432x368)
W0811 18:03:35.499779 547506102288 deprecation_wrapper.py:119] From /home/will/tf-pose-estimation/tf_pose/estimator.py:311: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

W0811 18:03:35.500979 547506102288 deprecation_wrapper.py:119] From /home/will/tf-pose-estimation/tf_pose/estimator.py:312: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.

Traceback (most recent call last):
File "run_webcam.py", line 45, in 
e = TfPoseEstimator(get_graph_path(args.model), target_size=(w, h), trt_bool=str2bool(args.tensorrt))
File "/home/will/tf-pose-estimation/tf_pose/estimator.py", line 327, in init
use_calibration=True,
TypeError: create_inference_graph() got an unexpected keyword argument 'use_calibration'

**Comment by willfu** [comment]
@tilink @bdatdo0601 do you get the same fps as snowmasaya mentioned? Thanks.

**Comment by tilink** [comment]
@willfu I just did a reinstall on my TX2 of Jetpack 4.2.2, which has Tensorflow 1.14.0 (tensorflow-gpu 1.14.0+nv19.7) - using:
`python3 run_webcam.py --camera=1 --tensorrt=True`
I only got around 3-4 FPS :( and a latency of 2-3 seconds. I'm really surprised this is still so poor, off of a clean install.

@ildoonet Can you tell us what you're getting on your TX2? Do you have any suggestions for improving FPS and reducing latency?

**Comment by bdatdo0601** [comment]
@willfu I see only a slight increase using RT unfortunately (5-6 from from 4-5 FPS)

**Pull request merged**
