### PR TITLE
Modifies relative URLs for model paths

### PR DESCRIPTION
**Pull request by lesreaper**
- TF couldn't find models on first launch for image inferencing. Missed in the file re-organization.

### CODE REVIEW

**Comment by elmuz** [comment]
...or simply he expects to launch the code from repository root, eg:
`python3 src/run_webcam.py`
in that case it works fine.

**Comment by lesreaper** [comment]
Fair enough, hadn't tried that. I usually run my scripts from their respective folder, but to each their own.

**Comment by guofuzheng** [comment]
hello，i want to save the estimated video without the original image just the skeleton , what should i do ?

**Comment by ildoonet** [comment]
as @elmuz described.

**Pull request closed without merging**
