### PR TITLE
real-time poses estimation for videos file. 

### PR DESCRIPTION
**Pull request by Hosseinhashemiir**
- ` $ python3 src/run_video.py --model=mobilenet_thin_432x368 --video video.avi`

### CODE REVIEW

**Comment by ildoonet** [comment]
@Hosseinhashemiir Thanks for your sharing.

**Comment by henbucuoshanghai** [comment]
from video    how?

**Comment by deepak7376** [comment]
for processing any video file 
1- go to the run_webcam.py file
2- change ''int'' to "str" from line parser.add_argument('--camera', type=int, default=0) 
3- run the command  
python run_webcam.py --camera etcs/dance.mp4 --model mobilenet_v2_large

**Comment by XUXIN-CHN** [comment]
> for processing any video file
> 1- go to the run_webcam.py file
> 2- change ''int'' to "str" from line parser.add_argument('--camera', type=int, default=0)
> 3- run the command
> python run_webcam.py --camera etcs/dance.mp4 --model mobilenet_v2_large

thank you so much!

**Pull request merged**
